name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo Deploying
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku git:remote -a fashion-pipeline-api
          git push heroku master
