name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-deploy
        run: |
          echo Deploying
          curl https://cli-assets.heroku.com/install.sh | sh
          export HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}}
          heroku login
          git push heroku master
